# Generated by Django 5.1.3 on 2024-12-02 17:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=5000)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "overall_progress",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(100),
                            django.core.validators.MinValueValidator(0),
                        ]
                    ),
                ),
            ],
            options={
                "db_table": "Projects",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("email_id", models.EmailField(max_length=100)),
                ("password", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "User",
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydesk.project"
                    ),
                ),
            ],
            options={
                "db_table": "Teams",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("MNG", "Manager"),
                            ("SM", "Scrum Master"),
                            ("TL", "Team Lead"),
                            ("A", "Associate"),
                            ("JA", "Jr Associate"),
                        ],
                        default="A",
                        max_length=3,
                    ),
                ),
                ("Availability", models.BooleanField()),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydesk.team"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydesk.user"
                    ),
                ),
            ],
            options={
                "db_table": "Team-Members",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=2000)),
                ("due_date", models.DateField()),
                ("assigned_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NS", "Not Started"),
                            ("IP", "In Progress"),
                            ("DELY", "Delayed"),
                            ("CMP", "Completed"),
                            ("CNCL", "Cancelled"),
                            ("BLK", "Blocked"),
                        ],
                        default="NS",
                        max_length=4,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydesk.project"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mydesk.user",
                    ),
                ),
            ],
            options={
                "db_table": "Tasks",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(max_length=500)),
                ("time_stamp", models.DateTimeField()),
                ("status", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mydesk.user"
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
            },
        ),
        migrations.CreateModel(
            name="MessageTableUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("time_stamp", models.DateTimeField()),
                (
                    "reciver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reciver_user",
                        to="mydesk.user",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sender_user",
                        to="mydesk.user",
                    ),
                ),
            ],
            options={
                "db_table": "user-messages",
            },
        ),
        migrations.CreateModel(
            name="MessageTableTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("time_stamp", models.DateTimeField()),
                (
                    "reciver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mydesk.team",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mydesk.user",
                    ),
                ),
            ],
            options={
                "db_table": "team-messages",
            },
        ),
    ]
