# Generated by Django 5.1.3 on 2024-12-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mydesk", "0003_rename_email_id_user_mail_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("NA", "Not Assigned"),
                    ("NS", "Not Started"),
                    ("IP", "In Progress"),
                    ("DELY", "Delayed"),
                    ("CMP", "Completed"),
                    ("CNCL", "Cancelled"),
                    ("BLK", "Blocked"),
                ],
                default="NS",
                max_length=4,
            ),
        ),
    ]
