# Generated by Django 5.1.4 on 2024-12-24 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydesk', '0005_alter_messagetableteam_sender_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailid',
            old_name='mail_id',
            new_name='email',
        ),
    ]
